---


- name: mkdir app backup dir
  become: yes
  become_user: root
  file:
    path: "/app/backup"
    state: directory
    owner: waming
    group: waming
    mode: 0755

- name: app backup 
  remote_user: waming
  command: "cp -a {{ wm_project_path }}/{{ wm_project }} /app/backup/"
  register: result
  ignore_errors: True

- name: app backup time
  remote_user: waming
  shell: "cp -a /app/backup/{{ wm_project }} /app/backup/{{ wm_project }}{{ backup_time }}"
  when: result | succeeded

- name: app copy
  remote_user: waming
  copy:
    src: "{{ wm_package_path }}/{{ wm_package }}"
    dest: "{{ wm_project_path }}"
    force: yes

- name: check app port is opened
  wait_for:
    host: "{{ groups['wm'][0] }}"
    port: "{{ wm_project_port }}"
    timeout: 30
