---

- name: check the fastdfs Tracker port is opened
  wait_for:
    host: "{{ tracker_server }}"
    port: "{{ tracker_port }}"
    timeout: 5
  delegate_to: 127.0.0.1
  ignore_errors: True
  run_once: true
  register: fastdfs_tracker_running

- name: check the fastdfs storage port is opened
  wait_for:
    host: "{{ storage_server }}"
    port: "{{ storage_port }}"
    timeout: 5
  delegate_to: 127.0.0.1
  ignore_errors: True
  run_once: true
  register: fastdfs_storage_running

- name: check the service port is opened
  wait_for:
    host: "{{ groups['wm'][0] }}"
    port: "{{ nginx_port }}"
    timeout: 5
  delegate_to: 127.0.0.1
  ignore_errors: True
  run_once: true
  register: nginx_running

- name: yum install package
  become: yes
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
  with_items: 
      - "{{ yum_list }}"

- name: copy fastdfs package to client
  copy:
    src: "{{ item }}"
    dest: /tmp/
  with_fileglob:
    - files/*

- name: install fastdfs
  include: "install_fastdfs.yaml"
  when: fastdfs_running | failed

