---


- name: check the fdfs_tracker port is opened
  wait_for:
    host: "{{ item[0] }}"
    port: "{{ tracker_port }}"
    timeout: 5
  delegate_to: 127.0.0.1
  ignore_errors: True
  run_once: true
  register: fdfs_tracker_running
  with_together:
    - "{{ groups.fastdfs[0] }}"
  when: 'role == "all" or role=="tracker"'

- name: check the fdfs_storage port is opened
  wait_for:
    host: "{{ item[0] }}"
    port: "{{ storage_port }}"
    timeout: 5
  delegate_to: 127.0.0.1
  ignore_errors: True
  run_once: true
  register: fdfs_storage_running
  with_together:
    - "{{ groups.fastdfs }}"
  when: 'role=="all" or role=="storage"'

- name: yum install package
  become: yes
  become_user: root
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ yum_list }}"


- name: install fdfs_tracker
  include: "install_fdfs_tracker.yaml"
#  when: 'fdfs_tracker_running | failed and role=="tracker"'

#- name: install fdfs_storage
#  include: "install_fdfs_tracker.yaml"
#  when: 'fdfs_storage_running | failed and role=="storage"'

- name: install fdfs_nginx
  include: "install_nginx.yaml"
