---


# app部署
- name: app backup weather-app
  become: yes
  become_user: root
  command: "cp -a {{ wm_project_path }}/{{ wm_project }} /app/backup/"
  ignore_errors: True

- name: app backup time
  become: yes
  become_user: root
  shell: "cp -a /app/backup/{{ wm_project }} /app/backup/{{ wm_project }}{{ backup_time }}"
  ignore_errors: True

- name: copy weather-app
  become: yes
  become_user: root
  copy:
    src: "{{ wm_package_path }}/{{ wm_package }}"
    dest: "{{ wm_project_path }}"
    force: yes

- name: stop tomcat
  become: yes
  become_user: root
  command: "{{ tomcat_bin_path }}/shutdown.sh"
  async: 100
  poll: 1

# 检查端口
- name: check weather-app port is opened
  wait_for:
    host: "{{ groups['wm'][0] }}"
    port: "{{ wm_project_port }}"
    timeout: 30
  ignore_errors: True
  register: tomcat_running

- name: start tomcat
  become: yes
  become_user: root
  command: "{{ tomcat_bin_path }}/startup.sh"
  async: 100
  poll: 1
  when: tomcat_running | failed

