---


# 微服务部署
# 备份
- name: mkdir backup scheduler dir
  #become: yes
  #become_user: root
  file:
    path: "{{ wm_project_path }}/backup"
    state: directory
    owner: waming
    group: waming
    mode: 0755

- name: backup scheduler
  remote_user: waming
  command: "cp -a {{ wm_project_path }}/{{ item }} {{ wm_project_path }}/backup"
  with_items:
    - "{{ wm_project }}"
  register: result
  ignore_errors: True
  
- name: backup time
  remote_user: waming
  shell: "mv {{ wm_project_path }}/backup/{{ item }} {{ wm_project_path }}/backup/{{ item }}{{ backup_time }}"
  with_items:
    - "{{ wm_project }}"
  when: result | succeeded

# 删除老的service
- name: delete scheduler
  file:
    dest: "{{ wm_project_path }}/{{ item }}"
    state: absent
  with_items:
    - "{{ wm_project }}"

# 解压到远端服务器
- name: Unarchive scheduler
  unarchive:
    src: "{{ item[0] }}/{{ item[1] }}"
    dest: "{{ wm_project_path }}"
  with_together:
    - "{{ wm_package_path }}"
    - "{{ wm_package }}"

# 重启服务
- name: restart scheduler
  shell: "/bin/bash app.sh restart"
  args:
    chdir: "{{ wm_project_path }}/{{ item }}/"
  async: 60
  poll: 1
  with_items:  
    - "{{ wm_project }}"
