---
galaxy_info:
  author: Yubin
  description: waminghuaqing
  company: waminghuaqing
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
