---

# 微服务部署
# 备份
- name: mkdir weather-python backup dir
  become: yes
  become_user: root
  file:
    path: "{{ wm_project_path }}/backup"
    state: directory
    owner: waming
    group: waming
    mode: 0755

- name: weather-python backup
  become: yes
  become_user: root
  command: "cp -a {{ wm_project_path }}/{{ wm_project }} {{ wm_project_path }}/backup"
  register: result
  ignore_errors: True

- name: weather-python backup time
  become: yes
  become_user: root
  shell: "mv {{ wm_project_path }}/backup/{{ wm_project }} {{ wm_project_path }}/backup/{{ wm_project }}{{ backup_time }}"
  when: result | succeeded

# 删除老的lib
- name: delete weather-python lib
  become: yes
  become_user: root
  file:
    dest: "{{ wm_project_path }}/{{ wm_project }}"
    state: absent

# 解压到远端服务器
- name: Unarchive weather-python
  become: yes
  become_user: root
  unarchive:
    src: "{{ wm_package_path }}/{{ wm_package }}"
    dest: "{{ wm_project_path }}"

# 重启服务
- name: restart weather-python
  become: yes
  become_user: root
  shell: /bin/bash start.sh
  args:
    chdir: "{{ wm_project_path }}/{{ wm_project }}/bin/"
  async: 60
  poll: 1

# 检查端口
- name: check weather-python port is opened
  become: yes
  become_user: root
  wait_for:
    host: "{{ item[0] }}"
    port: "{{ wm_project_port }}"
    timeout: 30
  with_together:
    - "{{ groups['python'] }}"
