---

# 微服务部署
# 备份
- name: mkdir weather-web backup dir
  become: yes
  become_user: root
  file:
    path: "{{ wm_project_path }}/backup"
    state: directory
    owner: waming
    group: waming
    mode: 0755

- name: weather-web backup
  remote_user: waming
  command: "cp -a {{ wm_project_path }}/{{ wm_project }} {{ wm_project_path }}/backup"
  register: result
  ignore_errors: True

- name: weather-web backup time
  remote_user: waming
  shell: "mv {{ wm_project_path }}/backup/{{ wm_project }} {{ wm_project_path }}/backup/{{ wm_project }}{{ backup_time }}"
  when: result | succeeded

# 删除老的lib
- name: delete weather-web
  file:
    dest: "{{ wm_project_path }}/{{ wm_project }}"
    state: absent

# 解压到远端服务器
- name: Unarchive weather-web
  unarchive:
    src: "{{ wm_package_path }}/{{ wm_package }}"
    dest: "{{ wm_project_path }}"

# 重启服务
- name: restart weather-web
  shell: /bin/bash app.sh restart
  args:
    chdir: "{{ wm_project_path }}/{{ wm_project }}"
  async: 120
  poll: 1

# 检查端口
- name: check weather-web port is opened
  wait_for:
    host: "{{ item[0] }}"
    port: "{{ wm_project_port }}"
    timeout: 10
  #with_items:
  with_together:
    - "{{ groups.wm }}"
  #ignore_errors: True
