---

- name: restart nginx
  become: yes
  become_user: root
  #command: systemctl status nginx.service  
  service:
    name: nginx
    state: restarted
    pattern: nginx

- name: reload nginx
  become: yes
  become_user: root
  service:
    name: nginx
    state: reloaded
    pattern: nginx
