---

- name: stop zookeeper
  become: yes
  become_user: root
  command: "{{ zk_path }}/bin/zkServer.sh stop"

- name: start tomcat
  become: yes
  become_user: root
  command: "{{ zk_path }}/bin/zkServer.sh start"
  # async: 30
  # poll: 1

- name: restart zookeeper
  become: yes
  become_user: root
  command: "{{ zk_path }}/bin/zkServer.sh restart"
