---


- name: copy tomcat8.tar.gz to client
  copy:
    src: tomcat8.tar.gz
    dest: /tmp/tomcat8.tar.gz

- name: Unarchive tomcat
  unarchive:
    src: /tmp/tomcat8.tar.gz
    dest: /tmp
    remote_src: True

- name: mkdir tomcat_path dir
  become: yes
  become_user: root
  file:
    path: "{{ tomcat_path }}"
    state: directory
    owner: waming
    group: waming
    mode: 0755

- name: copy tomcat
  command: "cp -a /tmp/tomcat {{ tomcat_path }}/tomcat{{ item }}"
  with_items:
    - "{{ tomcat_port }}"

- name: create server.xml file
  # become: yes
  # become_user: root
  template:
    src: server.xml.j2
    dest: "{{ tomcat_path }}/tomcat{{ item[1] }}/conf/server.xml"
    mode: 0600
    backup: yes
  with_together:
    - "{{ tomcat_shutdown_port }}"
    - "{{ tomcat_port }}"
    - "{{ tomcat_ajp_port }}"
  notify:
    - stop tomcat
    - start tomcat

